image: alpine/edge
packages:
  - hugo
  - hut
oauth: "pages.sr.ht/PAGES:RW"
sources:
  - https://git.sr.ht/~sircmpwn/sourcehut.org
tasks:
- build: |
    cd sourcehut.org
    hugo
- upload: |
    cd sourcehut.org
    hut pages publish -d sourcehut.org ./public/
