name: Publish and Flush

on:
  push:
    branches:
      - default
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write # Give the default GITHUB_TOKEN write permission to commit and push the added or changed files to the repository.
    # concurrency:
      # group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: 'docs'
          sparse-checkout-cone-mode: false
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Move files to root
        run: |
          ls -lah
          shopt -s dotglob
          mv docs/* .
          rm -rf docs
          ls -lah
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public

      # - name: Delete Build Artifact
        # uses: joutvhu/delete-artifact@v2.0.1
        # with:
          # owner: mysrcs # optional Default is current owner.
          # repo: mysrcs.github.io # optional Default is current repository.
          # run-id: build # optional If github-token is specified, this is the run that artifacts will be deleted from.
          # token: # optional If this is not specified, the action will attempt to delete artifacts from the current repository and the current workflow run.
          # latest: # optional In the case of reruns, this can be useful to avoid duplicates
          # name: github-pages # optional The artifact to delete, multiple names can be supplied on new lines.
          # pattern: # optional A glob pattern matching the artifacts that should be deleted. Ignored if name is specified.

  # Delete workflows
  del_runs:
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Rubber1Duck/delete-old-workflow-runs@v0.4.0
        with:
          repository: mysrcs/hugooooo   # replace this with your own repository
          older-than-seconds: 100             # remove all workflow runs older than 1 day ( default 86400 )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
