name: work

on:
  # Runs on pushes targeting the default main branch
  push:
    branches: ["default"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Checkout
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.1
        with:
          hugo-version: '0.58.3'
      - name: Prepare Hugo
        run: |
          git submodule sync && git submodule update --init
      - name: Build
        run: make docs
      - name: add nojekyll
        run: touch ./docs/public/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        with:
          emptyCommits: false
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/public
  # Name of the step in job of the workflow run
      - name: Delete Build Artifact
  # You may pin to the exact commit or the version.
  # uses: joutvhu/delete-artifact@e8511ee448fc8cfa02508df13dc0c0974f20d52d
        uses: joutvhu/delete-artifact@v2.0.1
        with:
    # The name of the owner of the repo, this is the repository that artifacts will be deleted from. Default is current owner.
          owner: mysrcs # optional
    # The name of the repository, this is the repository that artifacts will be deleted from. Default is current repository.
          repo: mysrcs.github.io # optional
    # The id of the workflow run where the desired delete artifact was uploaded from. If github-token is specified, this is the run that artifacts will be deleted from.
          run-id: build # optional
    # The GitHub token used to authenticate with the GitHub API. This is required when deleting artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to delete artifacts from the current repository and the current workflow run.
    #     token: # optional
    # Filter the workflow run's artifacts to the latest by name In the case of reruns, this can be useful to avoid duplicates
    #     latest: # optional
    # The name of the artifact to delete, multiple names can be supplied on new lines.
          name: github-pages # optional
    # A glob pattern matching the artifacts that should be deleted. Ignored if name is specified.
    #     pattern: # optional

  # Delete workflows
  del_runs:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Rubber1Duck/delete-old-workflow-runs@v0.4.0
        with:
          repository: mysrcs/hugooooo   # replace this with your own repository
          older-than-seconds: 80             # remove all workflow runs older than 1 day ( default 86400 )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
